/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

const fallbackProjectId = "tlgxotsqdlqgmmcovzns";
const fallbackAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRsZ3hvdHNxZGxxZ21tY292em5zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc1MDQyMTksImV4cCI6MjA5MzA4MDIxOX0.hhd2RUq3-Ln9xuocV8RmJiqmpscvaEs29r7w4aq7DVw";

const envSupabaseUrl = import.meta.env.VITE_SUPABASE_URL as string | undefined;
const envSupabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY as string | undefined;

const envProjectId = envSupabaseUrl?.match(/^https:\/\/([a-z0-9-]+)\.supabase\.co$/i)?.[1];

function getSettingsConfig(): { projectId?: string; anonKey?: string } {
	if (typeof window === 'undefined') {
		return {};
	}

	try {
		const raw = localStorage.getItem('esmark_settings');
		if (!raw) return {};

		const settings = JSON.parse(raw) as Record<string, unknown>;

		const projectIdFromSettings =
			(typeof settings.supabase_project_id === 'string' && settings.supabase_project_id) ||
			(typeof settings.project_id === 'string' && settings.project_id) ||
			undefined;

		const supabaseUrlFromSettings =
			(typeof settings.supabase_url === 'string' && settings.supabase_url) ||
			undefined;

		const urlDerivedProjectId = supabaseUrlFromSettings
			?.match(/^https:\/\/([a-z0-9-]+)\.supabase\.co$/i)?.[1];

		const anonKeyFromSettings =
			(typeof settings.supabase_anon_key === 'string' && settings.supabase_anon_key) ||
			(typeof settings.supabase_public_key === 'string' && settings.supabase_public_key) ||
			(typeof settings.supabase_key === 'string' && settings.supabase_key) ||
			undefined;

		return {
			projectId: projectIdFromSettings || urlDerivedProjectId,
			anonKey: anonKeyFromSettings,
		};
	} catch {
		return {};
	}
}

const settingsConfig = getSettingsConfig();

export const projectId = envProjectId || settingsConfig.projectId || fallbackProjectId;
export const publicAnonKey = envSupabaseAnonKey || settingsConfig.anonKey || fallbackAnonKey;
